goofish:
  cookies-str: ${COOKIES_STR}
  api-url: https://h5api.m.goofish.com/h5/
  get-token-uri: "mtop.taobao.idlemessage.pc.login.token/1.0/"
  get-iteminfo-uri: "mtop.taobao.idle.pc.detail/1.0/"
  socket-url: "wss://wss-goofish.dingtalk.com/"
  https-url: "https://www.goofish.com"
  login-check-url: "https://passport.goofish.com/newlogin/hasLogin.do"
  upload-url: "https://stream-upload.goofish.com/api/upload.api"
  heartbeat:
    interval: 15
    timeout: 60 # timeout should greater than interval
  token:
    refresh-interval: 3600
    retry-interval: 300
  historical-data-maximum: 30 # too much may complain Max frame length of .. has been exceeded.
  system-prompt: "classpath:prompts/system-prompt.txt"
  emotion-prompt: "classpath:prompts/emotion-prompt.txt"

  # Logging
logging:
  level:
    root: INFO
    org.springframework.r2dbc: DEBUG #DEBUG
    org.automation.goofish.core.socket: TRACE #TRACE
    org.springframework.ai: DEBUG

spring:
  sql:
    init:
      mode: ALWAYS

      schema-locations: classpath:schema.sql
  r2dbc:
    url: r2dbc:h2:file:///./data/goofish
    username: sa
    password:
  data:
    r2dbc:
      repositories:
        enabled: true
  h2:
    console:
      enabled: true
      path: /h2-console
  ai:
    chat:
      client:
        enabled: true
    dashscope:
      api-key: ${AI_DASHSCOPE_API_KEY}
      chat:
        options:
          model: qwen-max
          #tongyi-intent-detect-v3
          #qwen-plus
          #qwen-max
          #deepseek-r1