# 动态提示词配置（支持热更新）
version: 2.2
config:
  # 动态权重设置
  weight_decay:
    base: 0.7    # 衰减基数
    min: 0.1     # 最低权重
    recent: 3    # 高权重消息条数

  # 标签预解析规则
  tag_rules:
    - id: "20000##品牌"
      alias: "brand"
    - id: "20879##成色"
      alias: "condition"
    - id: "352716991##卡牌类型"
      alias: "card_type"

  # 场景模板
  templates:
    price_negotiation: |
      {# 价格谈判模板 #}
      {% if offer_history %}
      历史还价记录：{% for o in offer_history %}{{o.price}}元({{o.time|date('HH:mm')}}){% if not loop.last %}, {% endif %}{% endfor %}
      当前最低价：{{item.price * (1 - 0.1 * level)|round}}元（{{tags.condition}}）
      {% else %}
      首发价：{{item.price}}元（{{tags.brand}}正品）
      {% endif %}

    product_query: |
      {# 商品咨询模板 #}  
      {{tags.brand}} {{tags.card_type}}（{{tags.condition}}）
      详情：{{item.desc|truncate(30)}}

  # 安全规则
  security:
    blocked_phrases:
      - "微信"
      - "电话"
      - "支付宝"
    max_price_drop: 0.1  # 最大降价幅度