name: Run Service

on:
  workflow_dispatch:
    inputs:
      api_key:
        description: 'API Key'
        required: true
      cookies:
        description: 'Cookies'
        required: true

jobs:
  run-service:
    runs-on: ubuntu-latest

    steps:
      - name: Pull Docker image
        run: docker pull qoeop/xianyuautoagent:latest

      - name: Run Docker container
        run: |
          docker run -d \
            --name my_service_container \
            -e AI_DASHSCOPE_API_KEY='${{ github.event.inputs.api_key }}' \
            -e COOKIES_STR='${{ github.event.inputs.cookies }}' \
            qoeop/xianyuautoagent:latest

      - name: Output Docker logs and keep alive
        run: |
          echo "Displaying logs and keeping container alive..."
          while :; do
            docker logs --tail 10 -f my_service_container &
            CONTAINER_STATUS=$(docker inspect -f '{{.State.Running}}' my_service_container)
            if [ "$CONTAINER_STATUS" = "false" ]; then
              echo "Container has stopped unexpectedly. Exiting..."
              exit 1
            fi
            sleep 60
          done
